/**
 * System-wide Constants
 * Tasks: BE-010, BE-021
 * SRS Traceability: Section 10 (Data Requirements), FR-01 (Authentication)
 */

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
}

export const TRANSFER_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
}

export const TRANSFER_TYPE = {
  STORE_TO_STORE: 'STORE_TO_STORE',
  DEPARTMENT_TO_DEPARTMENT: 'DEPARTMENT_TO_DEPARTMENT',
}

export const REQUISITION_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  PARTIALLY_ISSUED: 'PARTIALLY_ISSUED',
  FULLY_ISSUED: 'FULLY_ISSUED',
  CANCELLED: 'CANCELLED',
}

export const SIV_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  ISSUED: 'ISSUED',
  CANCELLED: 'CANCELLED',
}

export const STOCK_TAKE_STATUS = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  RECONCILED: 'RECONCILED',
  CANCELLED: 'CANCELLED',
}

export const DISPOSAL_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
}

export const SHELF_LIFE_STATUS = {
  GOOD: 'GOOD',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
}

export const TRANSACTION_TYPE = {
  RECEIPT: 'RECEIPT',
  ISSUE: 'ISSUE',
  TRANSFER: 'TRANSFER',
  ADJUSTMENT: 'ADJUSTMENT',
  DISPOSAL: 'DISPOSAL',
}

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
}

export const SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
}

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  EXPORT: 'EXPORT',
}

export const NOTIFICATION_TYPES = {
  INFO: 'info',
  WARNING: 'warning',
  DANGER: 'danger',
  SUCCESS: 'success',
}
