/**
 * Frontend Permission Checking Utility
 * Mirrors backend RBAC matrix from backend/src/config/rbac.js & SRS Appendix C
 */

export const PERMISSIONS = {
  // Auth & User Management
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DEACTIVATE: 'users:deactivate',
  USERS_MANAGE: 'users:manage',

  ROLES_CREATE: 'roles:create',
  ROLES_READ: 'roles:read',
  ROLES_UPDATE: 'roles:update',
  ROLES_DELETE: 'roles:delete',
  ROLES_MANAGE: 'roles:manage',
  ROLES_ASSIGN: 'roles:assign',

  PERMISSIONS_READ: 'permissions:read',

  // Master Data
  STORES_MANAGE: 'stores:manage',
  STORES_READ: 'stores:read',
  DEPARTMENTS_MANAGE: 'departments:manage',
  DEPARTMENTS_READ: 'departments:read',
  CATEGORIES_MANAGE: 'categories:manage',
  CATEGORIES_READ: 'categories:read',
  ITEMS_MANAGE: 'items:manage',
  ITEMS_READ: 'items:read',
  UNITS_MANAGE: 'units:manage',
  UNITS_READ: 'units:read',
  SUPPLIERS_MANAGE: 'suppliers:manage',
  SUPPLIERS_READ: 'suppliers:read',
  LOCATIONS_MANAGE: 'locations:manage',
  LOCATIONS_READ: 'locations:read',
  MASTER_DATA_READ: 'master-data:read',
  MASTER_DATA_VALIDATE: 'master-data:validate',
  MASTER_DATA_MANAGE: 'master-data:manage',

  // Goods Receiving & Inspection
  RECEIPTS_CREATE: 'receipts:create',
  RECEIPTS_READ: 'receipts:read',
  RECEIPTS_UPDATE: 'receipts:update',
  GOODS_RECEIPT_CREATE: 'goods-receipt:create',
  GOODS_RECEIPT_READ: 'goods-receipt:read',
  GOODS_RECEIPT_UPDATE: 'goods-receipt:update',

  EVALUATIONS_READ: 'evaluations:read',
  EVALUATIONS_CREATE: 'evaluations:create',
  EVALUATIONS_UPDATE: 'evaluations:update',
  EVALUATIONS_DECIDE: 'evaluations:decide',
  EVALUATIONS_MANAGE: 'evaluations:manage',

  GRN_CREATE: 'grn:create',
  GRN_GENERATE: 'grn:generate',
  GRN_READ: 'grn:read',
  GRN_UPDATE: 'grn:update',
  GRN_CANCEL: 'grn:cancel',

  // Stock & Bin Cards
  STOCK_CARDS_READ: 'stock_cards:read',
  BIN_CARDS_READ: 'bin_cards:read',
  BINS_TRANSFER: 'bins:transfer',

  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_POST: 'inventory:post',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_MANAGE: 'inventory:manage',

  // Requisitions
  REQUISITIONS_CREATE: 'requisitions:create',
  REQUISITIONS_READ: 'requisitions:read',
  REQUISITIONS_APPROVE: 'requisitions:approve',

  // SIV (Store Issue Voucher)
  SIV_PREPARE: 'siv:prepare',
  SIV_AMEND: 'siv:amend',
  SIV_APPROVE: 'siv:approve',
  SIV_FINALIZE: 'siv:finalize',

  // Assets
  ASSETS_REGISTER: 'assets:register',
  ASSETS_READ: 'assets:read',

  // Returns
  RETURNS_CREATE: 'returns:create',
  RETURNS_READ: 'returns:read',
  RETURNS_EVALUATE: 'returns:evaluate',
  RETURNS_APPROVE: 'returns:approve',

  // Transfers
  TRANSFERS_CREATE: 'transfers:create',
  TRANSFERS_READ: 'transfers:read',
  TRANSFERS_APPROVE: 'transfers:approve',
  TRANSFERS_EXECUTE: 'transfers:execute',

  // Disposal
  SHELFLIFE_READ: 'shelflife:read',
  DISPOSAL_REQUEST: 'disposal:request',
  DISPOSAL_APPROVE: 'disposal:approve',
  DISPOSAL_EXECUTE: 'disposal:execute',

  // Reconciliation & Stock Taking
  RECONCILIATION_CREATE: 'reconciliation:create',
  RECONCILIATION_READ: 'reconciliation:read',
  RECONCILIATION_APPROVE: 'reconciliation:approve',
  RECONCILIATION_POST: 'reconciliation:post',

  // Gate
  DISPATCH_VERIFY: 'dispatch:verify',

  // Reports & Audit
  REPORTS_VIEW: 'reports:view',
  AUDIT_READ: 'audit:read',
  AUDIT_MANAGE: 'audit:manage',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

/**
 * Role-to-permission mapping (strict separation of duties)
 * EXACT mirror of backend/src/config/rbac.js MATRIX
 */
const ROLE_PERMISSIONS: Record<string, string[]> = {
  // ADMIN: Full system administration per SRS Appendix C
  ADMIN: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.STORES_MANAGE,
    PERMISSIONS.STORES_READ,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.DEPARTMENTS_READ,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ITEMS_MANAGE,
    PERMISSIONS.ITEMS_READ,
    PERMISSIONS.UNITS_MANAGE,
    PERMISSIONS.UNITS_READ,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.LOCATIONS_MANAGE,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.MASTER_DATA_VALIDATE,
    PERMISSIONS.MASTER_DATA_MANAGE,
    PERMISSIONS.RECEIPTS_CREATE,
    PERMISSIONS.RECEIPTS_READ,
    PERMISSIONS.RECEIPTS_UPDATE,
    PERMISSIONS.GOODS_RECEIPT_CREATE,
    PERMISSIONS.GOODS_RECEIPT_READ,
    PERMISSIONS.GOODS_RECEIPT_UPDATE,
    PERMISSIONS.EVALUATIONS_READ,
    PERMISSIONS.EVALUATIONS_CREATE,
    PERMISSIONS.EVALUATIONS_UPDATE,
    PERMISSIONS.EVALUATIONS_DECIDE,
    PERMISSIONS.EVALUATIONS_MANAGE,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_GENERATE,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.GRN_UPDATE,
    PERMISSIONS.GRN_CANCEL,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.BIN_CARDS_READ,
    PERMISSIONS.BINS_TRANSFER,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_POST,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.REQUISITIONS_CREATE,
    PERMISSIONS.REQUISITIONS_READ,
    PERMISSIONS.REQUISITIONS_APPROVE,
    PERMISSIONS.SIV_PREPARE,
    PERMISSIONS.SIV_AMEND,
    PERMISSIONS.SIV_APPROVE,
    PERMISSIONS.SIV_FINALIZE,
    PERMISSIONS.ASSETS_REGISTER,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.RETURNS_CREATE,
    PERMISSIONS.RETURNS_READ,
    PERMISSIONS.RETURNS_EVALUATE,
    PERMISSIONS.RETURNS_APPROVE,
    PERMISSIONS.TRANSFERS_CREATE,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.TRANSFERS_EXECUTE,
    PERMISSIONS.SHELFLIFE_READ,
    PERMISSIONS.DISPOSAL_REQUEST,
    PERMISSIONS.DISPOSAL_APPROVE,
    PERMISSIONS.DISPOSAL_EXECUTE,
    PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.RECONCILIATION_APPROVE,
    PERMISSIONS.RECONCILIATION_POST,
    PERMISSIONS.DISPATCH_VERIFY,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_MANAGE,
  ],

  // PAO: Property Administration Officer — supervision, approvals, master data per SRS Appendix C
  // PAO does NOT manage users — user management is ADMIN-only
  PAO: [
    PERMISSIONS.STORES_MANAGE,
    PERMISSIONS.STORES_READ,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.DEPARTMENTS_READ,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ITEMS_MANAGE,
    PERMISSIONS.ITEMS_READ,
    PERMISSIONS.UNITS_MANAGE,
    PERMISSIONS.UNITS_READ,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.LOCATIONS_MANAGE,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.MASTER_DATA_VALIDATE,
    PERMISSIONS.RECEIPTS_READ,
    PERMISSIONS.RECEIPTS_UPDATE,
    PERMISSIONS.GOODS_RECEIPT_READ,
    PERMISSIONS.GOODS_RECEIPT_UPDATE,
    PERMISSIONS.EVALUATIONS_READ,
    PERMISSIONS.EVALUATIONS_CREATE,
    PERMISSIONS.EVALUATIONS_UPDATE,
    PERMISSIONS.EVALUATIONS_DECIDE,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_GENERATE,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.GRN_UPDATE,
    PERMISSIONS.GRN_CANCEL,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.BIN_CARDS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REQUISITIONS_READ,
    PERMISSIONS.REQUISITIONS_APPROVE,
    PERMISSIONS.SIV_AMEND,
    PERMISSIONS.SIV_APPROVE,
    PERMISSIONS.SIV_FINALIZE,
    PERMISSIONS.ASSETS_REGISTER,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.RETURNS_CREATE,
    PERMISSIONS.RETURNS_READ,
    PERMISSIONS.RETURNS_EVALUATE,
    PERMISSIONS.RETURNS_APPROVE,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.TRANSFERS_EXECUTE,
    PERMISSIONS.SHELFLIFE_READ,
    PERMISSIONS.DISPOSAL_REQUEST,
    PERMISSIONS.DISPOSAL_APPROVE,
    PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.RECONCILIATION_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_READ,
  ],

  // STOREKEEPER: Store operations. Can READ stores but cannot create/delete them (ADMIN/PAO only).
  STOREKEEPER: [
    PERMISSIONS.STORES_READ,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.DEPARTMENTS_READ,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ITEMS_MANAGE,
    PERMISSIONS.ITEMS_READ,
    PERMISSIONS.UNITS_MANAGE,
    PERMISSIONS.UNITS_READ,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.LOCATIONS_MANAGE,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.MASTER_DATA_VALIDATE,
    PERMISSIONS.RECEIPTS_CREATE,
    PERMISSIONS.RECEIPTS_READ,
    PERMISSIONS.RECEIPTS_UPDATE,
    PERMISSIONS.GOODS_RECEIPT_CREATE,
    PERMISSIONS.GOODS_RECEIPT_READ,
    PERMISSIONS.GOODS_RECEIPT_UPDATE,
    PERMISSIONS.EVALUATIONS_READ,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_GENERATE,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.GRN_UPDATE,
    PERMISSIONS.GRN_CANCEL,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.BIN_CARDS_READ,
    PERMISSIONS.BINS_TRANSFER,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_POST,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.REQUISITIONS_READ,
    PERMISSIONS.SIV_PREPARE,
    PERMISSIONS.SIV_AMEND,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.RETURNS_READ,
    PERMISSIONS.RETURNS_APPROVE,
    PERMISSIONS.TRANSFERS_CREATE,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.TRANSFERS_EXECUTE,
    PERMISSIONS.SHELFLIFE_READ,
    PERMISSIONS.DISPOSAL_REQUEST,
    PERMISSIONS.DISPOSAL_EXECUTE,
    PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.RECONCILIATION_POST,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // TEC: Technical Evaluation Committee per SRS Appendix C
  TEC: [
    PERMISSIONS.STORES_READ,
    PERMISSIONS.DEPARTMENTS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ITEMS_READ,
    PERMISSIONS.UNITS_READ,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.RECEIPTS_READ,
    PERMISSIONS.GOODS_RECEIPT_READ,
    PERMISSIONS.EVALUATIONS_READ,
    PERMISSIONS.EVALUATIONS_CREATE,
    PERMISSIONS.EVALUATIONS_UPDATE,
    PERMISSIONS.EVALUATIONS_DECIDE,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.RETURNS_READ,
    PERMISSIONS.RETURNS_EVALUATE,
    PERMISSIONS.RETURNS_APPROVE,
    PERMISSIONS.SHELFLIFE_READ,
    PERMISSIONS.DISPOSAL_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // ACCOUNTANT: Financial reporting, valuation, fixed asset registration per SRS Appendix C
  ACCOUNTANT: [
    PERMISSIONS.STORES_READ,
    PERMISSIONS.DEPARTMENTS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ITEMS_READ,
    PERMISSIONS.UNITS_READ,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.RECEIPTS_READ,
    PERMISSIONS.GOODS_RECEIPT_READ,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.BIN_CARDS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ASSETS_REGISTER,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.SHELFLIFE_READ,
    PERMISSIONS.DISPOSAL_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // DEPARTMENT_HEAD: Requisition approval, departmental oversight per SRS Appendix C
  DEPARTMENT_HEAD: [
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REQUISITIONS_CREATE,
    PERMISSIONS.REQUISITIONS_READ,
    PERMISSIONS.REQUISITIONS_APPROVE,
    PERMISSIONS.RETURNS_CREATE,
    PERMISSIONS.RETURNS_READ,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // REQUESTER: Material requisitioning and status tracking per SRS Appendix C
  REQUESTER: [
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.STOCK_CARDS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REQUISITIONS_CREATE,
    PERMISSIONS.REQUISITIONS_READ,
    PERMISSIONS.RETURNS_CREATE,
    PERMISSIONS.RETURNS_READ,
  ],

  // SECURITY_OFFICER: Gate and dispatch verification per SRS Appendix C
  SECURITY_OFFICER: [
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.DISPATCH_VERIFY,
    PERMISSIONS.REQUISITIONS_READ,
  ],

  // PROPERTY_REGISTRATION_OFFICER: Fixed asset registration per SRS Appendix C
  PROPERTY_REGISTRATION_OFFICER: [
    PERMISSIONS.MASTER_DATA_READ,
    PERMISSIONS.GRN_READ,
    PERMISSIONS.ASSETS_REGISTER,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.REPORTS_VIEW,
  ],
}

/**
 * Get all permissions for a set of roles
 */
export function getPermissionsForRoles(roles: string[]): string[] {
  const permissionSet = new Set<string>()
  for (const role of roles) {
    const perms = ROLE_PERMISSIONS[role] || []
    for (const p of perms) {
      permissionSet.add(p)
    }
  }
  return Array.from(permissionSet)
}

/**
 * Check if user has a specific permission (with :manage fallback)
 */
export function hasPermission(userRoles: string[], permission: string): boolean {
  const normalizedKey = permission.includes('.') && !permission.includes(':')
    ? permission.replace(/\./g, ':')
    : permission

  const perms = getPermissionsForRoles(userRoles)
  if (perms.includes(normalizedKey)) return true

  const [module, action] = normalizedKey.split(':')
  if (action !== 'manage' && perms.includes(`${module}:manage`)) {
    return true
  }

  return false
}

/**
 * Check if user has ANY of the listed permissions
 */
export function hasAnyPermission(userRoles: string[], permissions: string[]): boolean {
  return permissions.some((p) => hasPermission(userRoles, p))
}

/**
 * Check if user has ALL of the listed permissions
 */
export function hasAllPermissions(userRoles: string[], permissions: string[]): boolean {
  return permissions.every((p) => hasPermission(userRoles, p))
}

/**
 * Role display names
 */
export const ROLE_NAMES: Record<string, string> = {
  ADMIN: 'System Administrator',
  PAO: 'Property Administration Officer',
  STOREKEEPER: 'Storekeeper',
  TEC: 'Technical Evaluation Committee',
  ACCOUNTANT: 'Accountant',
  DEPARTMENT_HEAD: 'Department Head',
  REQUESTER: 'Department Requester',
  SECURITY_OFFICER: 'Security Officer',
  PROPERTY_REGISTRATION_OFFICER: 'Property Registration Officer',
}
